title: Survival Swimming Diary
description: 기술, 철학, 예술을 담은 일지
baseurl: ""
url: "https://survivalswimmingdiary.com"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

gems:
  - jekyll-sitemap


